# Generated by Django 4.2.7 on 2025-01-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotherBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('producer', models.CharField(max_length=100)),
                ('wiifAndBluetooth', models.BooleanField()),
                ('socketIsLGA', models.BooleanField()),
                ('size', models.CharField(choices=[('ATX', 'ATX'), ('MC', 'Micro-ATX'), ('MIN', 'Mini-ATX'), ('E', 'eATX')], default='ATX', max_length=3)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
