# Generated by Django 4.2.7 on 2025-01-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('producer', models.CharField(max_length=50)),
                ('clockSpeed', models.IntegerField()),
                ('cores', models.IntegerField()),
                ('socketIsLGA', models.BooleanField()),
                ('overclocking', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='motherboard',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='size',
            field=models.CharField(choices=[('ATX', 'ATX'), ('MC', 'Micro-ATX'), ('MIN', 'Mini-ITX'), ('E', 'eATX')], default='ATX', max_length=3),
        ),
    ]
