# Generated by Django 4.2.7 on 2025-01-08 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_cpu_motherboard_count_alter_motherboard_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motherboard',
            name='count',
        ),
    ]
