# Generated by Django 4.2.7 on 2025-01-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_motherboard_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('producer', models.CharField(max_length=100)),
                ('vRam', models.IntegerField()),
                ('size', models.IntegerField()),
                ('consumption', models.IntegerField()),
                ('description', models.CharField(default='a', max_length=200)),
                ('price', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('producer', models.CharField(max_length=100)),
                ('output', models.IntegerField()),
                ('efficiency', models.IntegerField()),
                ('fanSize', models.IntegerField()),
                ('description', models.CharField(default='a', max_length=200)),
                ('price', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('producer', models.CharField(max_length=100)),
                ('ddr', models.CharField(choices=[(3, 'DDR3'), (4, 'DDR4'), (5, 'DDR5')], default=5, max_length=1)),
                ('capacity', models.IntegerField()),
                ('description', models.CharField(default='a', max_length=200)),
                ('price', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='SSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('producer', models.CharField(max_length=100)),
                ('isSATA', models.BooleanField()),
                ('capacity', models.IntegerField()),
                ('description', models.CharField(default='a', max_length=200)),
                ('price', models.IntegerField(default='1')),
            ],
        ),
        migrations.AddField(
            model_name='cpu',
            name='description',
            field=models.CharField(default='a', max_length=200),
        ),
        migrations.AddField(
            model_name='cpu',
            name='price',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='description',
            field=models.CharField(default='a', max_length=200),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='producer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='price',
            field=models.IntegerField(default='1'),
        ),
    ]
